name: Internal name links regression test

on:
  push:
    branches:
      - "main"
  pull_request:

jobs:
  test-internal-name-links:
    name: Test links to internal names
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Install elan and build doc-gen4
        uses: leanprover/lean-action@v1
        with:
          build-args: "--wfail"

      - name: Run internal name links test
        run: ./test/test-internal-name-links.sh
